// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { services } from "npm:@/data/services";
import { integrations } from "npm:@/data/integrations";
import { landingPages } from "npm:@/data/landingPages";
import { CALENDLY_URL } from "npm:@/lib/links";
var SITE = "https://orthoautomate.online";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Get OrthoAutomate's public company facts: what it does, who it serves, founder, service and page map, and how to book a call. Good starting point for any question about the business.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "OrthoAutomate",
      website: SITE,
      summary: "OrthoAutomate builds AI revenue-recovery systems for private dental and orthodontic clinics \u2014 a 24/7 AI receptionist, instant new-lead response, and automated treatment-plan follow-up that plug into the clinic's existing practice-management software.",
      founder: "Jashim Uddin, Founder & CEO",
      whoWeServe: "Private dental, orthodontic, implant and cosmetic clinics \u2014 single-location and multi-location groups \u2014 that lose revenue to missed calls, slow lead response, unaccepted treatment plans, no-shows and dormant patients.",
      promisedOutcome: "Recover more booked appointments and reduce revenue leakage without changing the software or workflow the front desk already uses.",
      operatesIn: "Worldwide (English and Arabic support)",
      setupTime: "Typically 72 hours from kickoff, fully managed setup.",
      bookACallUrl: CALENDLY_URL,
      services: services.map((s) => ({
        slug: s.slug,
        name: s.name,
        url: `${SITE}/services/${s.slug}`
      })),
      integrations: integrations.map((i) => ({
        slug: i.slug,
        name: i.name,
        url: `${SITE}/integrations/${i.slug}`
      })),
      landingPages: landingPages.map((p) => ({
        slug: p.slug,
        category: p.category,
        label: p.breadcrumbLabel,
        url: `${SITE}/${p.slug}`
      })),
      keyPages: [
        `${SITE}/`,
        `${SITE}/about`,
        `${SITE}/services`,
        `${SITE}/integrations`,
        `${SITE}/pricing`,
        `${SITE}/case-studies`,
        `${SITE}/roi-calculator`,
        `${SITE}/faq`,
        `${SITE}/blog`,
        `${SITE}/contact`,
        `${SITE}/security-and-privacy`
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { services as services2 } from "npm:@/data/services";
var SITE2 = "https://orthoautomate.online";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List every OrthoAutomate service (AI receptionist, instant lead response, treatment-plan follow-up) with slug, tagline, summary and page URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = services2.map((s) => ({
      slug: s.slug,
      name: s.name,
      shortName: s.shortName,
      tagline: s.tagline,
      summary: s.summary,
      url: `${SITE2}/services/${s.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { services as services3 } from "npm:@/data/services";
var SITE3 = "https://orthoautomate.online";
var get_service_default = defineTool3({
  name: "get_service",
  title: "Get service details",
  description: "Get the full public detail of one OrthoAutomate service: intro, outcomes, how it works, features, who it is best for, and its FAQs. Use list_services first to find the slug.",
  inputSchema: {
    slug: z.string().min(1).describe("Service slug, e.g. ai-receptionist, lead-response, treatment-followup.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const service = services3.find((s) => s.slug === slug.trim().toLowerCase());
    if (!service) {
      return {
        content: [
          {
            type: "text",
            text: `No service found for slug "${slug}". Available slugs: ${services3.map((s) => s.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const payload = { ...service, url: `${SITE3}/services/${service.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { service: payload }
    };
  }
});

// src/lib/mcp/tools/list-integrations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { integrations as integrations2 } from "npm:@/data/integrations";
var SITE4 = "https://orthoautomate.online";
var list_integrations_default = defineTool4({
  name: "list_integrations",
  title: "List PMS integrations",
  description: "List the dental practice-management systems OrthoAutomate integrates with (Dentrix, Open Dental, Eaglesoft, Curve Dental), including supported capabilities and setup timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = integrations2.map((i) => ({
      ...i,
      url: `${SITE4}/integrations/${i.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { integrations: items }
    };
  }
});

// src/lib/mcp/tools/search-faqs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { services as services4 } from "npm:@/data/services";
import { landingPages as landingPages2 } from "npm:@/data/landingPages";
var SITE5 = "https://orthoautomate.online";
var allFaqs = () => {
  const fromServices = services4.flatMap(
    (s) => s.faqs.map((f) => ({
      question: f.q,
      answer: f.a,
      source: s.shortName,
      url: `${SITE5}/services/${s.slug}`
    }))
  );
  const fromLanding = landingPages2.flatMap(
    (p) => p.faqs.map((f) => ({
      question: f.q,
      answer: f.a,
      source: p.breadcrumbLabel,
      url: `${SITE5}/${p.slug}`
    }))
  );
  return [...fromServices, ...fromLanding];
};
var search_faqs_default = defineTool5({
  name: "search_faqs",
  title: "Search FAQs",
  description: "Search OrthoAutomate's published FAQ answers about pricing, setup time, integrations, HIPAA/compliance, AI call handling and results. Omit the query to get every FAQ.",
  inputSchema: {
    query: z2.string().describe("Keywords to match against questions and answers. Use an empty string for all FAQs."),
    limit: z2.number().int().min(1).max(50).describe("Maximum number of FAQs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.trim().toLowerCase();
    const terms = q.split(/\s+/).filter(Boolean);
    const scored = allFaqs().map((f) => {
      const haystack = `${f.question} ${f.answer}`.toLowerCase();
      const score = terms.length ? terms.reduce((acc, t) => acc + (haystack.includes(t) ? 1 : 0), 0) : 1;
      return { ...f, score };
    }).filter((f) => f.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map(({ score: _score, ...rest }) => rest);
    return {
      content: [{ type: "text", text: JSON.stringify(scored, null, 2) }],
      structuredContent: { faqs: scored, count: scored.length }
    };
  }
});

// src/lib/mcp/tools/list-case-studies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { caseStudies } from "npm:@/data/caseStudies";
var SITE6 = "https://orthoautomate.online";
var list_case_studies_default = defineTool6({
  name: "list_case_studies",
  title: "List case studies",
  description: "List OrthoAutomate's published client case studies with clinic, location, service used, headline metrics, challenge, solution and result.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = caseStudies.map((c) => ({
      ...c,
      url: `${SITE6}/case-studies/${c.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { caseStudies: items }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { articles } from "npm:@/data/articles";
var SITE7 = "https://orthoautomate.online";
var list_articles_default = defineTool7({
  name: "list_articles",
  title: "List blog articles",
  description: "List OrthoAutomate blog articles with slug, title, one-sentence summary, author, publish/update dates and tags. Use get_article to read the full text.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = articles.map((a) => ({
      slug: a.slug,
      title: a.title,
      summary: a.summary,
      author: a.author,
      publishedAt: a.publishedAt,
      updatedAt: a.updatedAt,
      readingMinutes: a.readingMinutes,
      tags: a.tags,
      url: `${SITE7}/blog/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { articles: items }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { articles as articles2 } from "npm:@/data/articles";
var SITE8 = "https://orthoautomate.online";
var get_article_default = defineTool8({
  name: "get_article",
  title: "Get blog article",
  description: "Read the full text of one OrthoAutomate blog article as markdown, including all sections and subsections. Use list_articles to find the slug.",
  inputSchema: {
    slug: z3.string().min(1).describe("Article slug from list_articles.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const article = articles2.find((a) => a.slug === slug.trim().toLowerCase());
    if (!article) {
      return {
        content: [
          {
            type: "text",
            text: `No article found for slug "${slug}". Available slugs: ${articles2.map((a) => a.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const lines = [
      `# ${article.title}`,
      "",
      `By ${article.author} \u2014 published ${article.publishedAt}, updated ${article.updatedAt}`,
      "",
      article.intro,
      ""
    ];
    for (const section of article.sections) {
      lines.push(`## ${section.heading}`, "");
      for (const p of section.paragraphs ?? []) lines.push(p, "");
      for (const b of section.bullets ?? []) lines.push(`- ${b}`);
      if (section.bullets?.length) lines.push("");
      for (const sub of section.subsections ?? []) {
        lines.push(`### ${sub.heading}`, "");
        for (const p of sub.paragraphs) lines.push(p, "");
      }
    }
    const markdown = lines.join("\n").trim();
    const url = `${SITE8}/blog/${article.slug}`;
    return {
      content: [{ type: "text", text: `${markdown}

Source: ${url}` }],
      structuredContent: { slug: article.slug, title: article.title, url, markdown }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "orthoautomate-mcp",
  title: "OrthoAutomate",
  version: "0.1.0",
  instructions: "Public tools for OrthoAutomate, an AI revenue-recovery service for dental and orthodontic clinics. Start with `get_company_info` for an overview and the page map. Use `list_services` / `get_service` for service detail, `list_integrations` for supported practice-management systems (Dentrix, Open Dental, Eaglesoft, Curve Dental), `search_faqs` for pricing, setup, compliance and results questions, `list_case_studies` for client outcomes, and `list_articles` / `get_article` to read published articles. All data is public marketing content from orthoautomate.online.",
  tools: [
    get_company_info_default,
    list_services_default,
    get_service_default,
    list_integrations_default,
    search_faqs_default,
    list_case_studies_default,
    list_articles_default,
    get_article_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
