// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/data/services.ts
var services = [
  {
    slug: "ai-receptionist",
    name: "24/7 AI Receptionist for Dental Clinics",
    shortName: "AI Receptionist",
    tagline: "Answer every call in under 2 seconds. Day, night, weekends, holidays.",
    summary: "A 24/7 AI phone receptionist for dental clinics that captures every missed call, books appointments into your calendar, and routes urgent cases to your team \u2014 recovering $40K\u2013$120K/year in walked-away production.",
    intro: "Between huddles, lunch, the after-work spike, weekends, and holidays, the average private dental clinic misses 18\u201335% of inbound calls. Each missed new-patient call is worth $600\u2013$1,200 in first-visit production \u2014 $4K\u2013$25K in lifetime value for ortho, implants, or full-arch consults. Our AI receptionist closes that gap, permanently.",
    outcomes: [
      { value: "<2s", label: "Average pickup time" },
      { value: "<3%", label: "Missed-call rate after install" },
      { value: "60\u201380%", label: "Recovered calls that book" }
    ],
    howItWorks: [
      {
        title: "We learn your clinic",
        body: "We train the AI on your services, hours, providers, insurance accepted, FAQs, and brand tone \u2014 so it sounds like a member of your team, not a robot."
      },
      {
        title: "We connect your PMS & phone",
        body: "Direct integration with Dentrix, Open Dental, Eaglesoft, or Curve plus your VoIP provider (RingCentral, Weave, Mango, etc.). Live in 72 hours."
      },
      {
        title: "AI answers every call, 24/7",
        body: "Books appointments straight into the calendar, answers FAQs, collects insurance details, and instantly transfers to a human for emergencies or clinical questions."
      }
    ],
    features: [
      "Sub-2-second pickup, 24/7/365 \u2014 no voicemail, no missed calls",
      "Direct calendar booking into Dentrix, Open Dental, Eaglesoft, Curve",
      "Bilingual support (English + Spanish) on request",
      "Real-time human escalation with full conversation context",
      "Caller transcripts and call recordings logged to your PMS",
      "Custom voice + brand tone \u2014 sounds like your front desk",
      "HIPAA-conscious infrastructure, encrypted at rest and in transit"
    ],
    bestFor: [
      "Private practices losing 15%+ of inbound calls",
      "Clinics where the front desk is overwhelmed at peak hours",
      "Multi-location DSOs needing consistent call-handling across sites",
      "Specialty practices (ortho, implants, cosmetic) with high-value calls"
    ],
    faqs: [
      {
        q: "How is this different from a voicemail or call-overflow service?",
        a: "Voicemail loses 80%+ of new-patient callers \u2014 they hang up and call a competitor. A traditional overflow service answers as a generic call center, doesn't know your providers or insurance, and can't book into your PMS. Our AI receptionist books directly into your calendar, knows your services and pricing, and sounds like your front desk."
      },
      {
        q: "Can patients tell they're talking to AI?",
        a: "Most can't. The AI uses natural conversational tone, handles interruptions, and adapts to accents. When a caller explicitly asks for a human or has an emergency, the call is transferred instantly with full context."
      },
      {
        q: "What happens during a real dental emergency?",
        a: "The AI is trained to identify emergency keywords (swelling, severe pain, trauma, broken tooth) and immediately routes the call to your on-call number or after-hours line with the patient's name, callback number, and a 1-sentence summary of the issue."
      },
      {
        q: "Does it integrate with Dentrix and Open Dental?",
        a: "Yes \u2014 direct calendar and patient-record integrations with Dentrix, Open Dental, Eaglesoft, and Curve are included. We handle 100% of the technical setup."
      }
    ],
    relatedSlugs: ["lead-response", "treatment-followup"]
  },
  {
    slug: "lead-response",
    name: "Instant AI Lead Response for Dental Ads",
    shortName: "Instant Lead Response",
    tagline: "Reply to every Google, Facebook, and Instagram lead in under 60 seconds.",
    summary: "An AI system that replies to every paid dental ad lead in under 60 seconds via SMS and DM \u2014 qualifying, booking, and re-engaging ghosted leads automatically. Typically doubles booking rate without changing ad spend.",
    intro: "Industry research is unambiguous: leads contacted within 5 minutes are roughly 100\xD7 more likely to qualify than leads contacted after 30 minutes. Most dental clinics take hours \u2014 sometimes days \u2014 to reply to a paid ad lead, while a competitor's auto-responder is already in the conversation. We close that gap to under 60 seconds.",
    outcomes: [
      { value: "<60s", label: "Average response time" },
      { value: "8\xD7", label: "Higher booking rate vs. human-only" },
      { value: "~50%", label: "Lower effective cost-per-booked-patient" }
    ],
    howItWorks: [
      {
        title: "We connect your lead sources",
        body: "Direct integrations with Google Ads lead forms, Facebook & Instagram Lead Ads, Meta Messenger, your website forms, and your CRM. Every new lead hits the AI in real time."
      },
      {
        title: "AI qualifies in 2\u20133 messages",
        body: "Conversational SMS / DM that confirms the service interest, insurance, location, and preferred time \u2014 without sounding like a survey."
      },
      {
        title: "Books or hands off, then re-engages",
        body: "Qualified leads are booked directly into the calendar. Ghosted leads get a 7\u201314 day re-engagement sequence that typically recovers 20\u201330% of them."
      }
    ],
    features: [
      "<60-second response across SMS, Instagram DM, and Facebook Messenger",
      "Lead qualification with 2\u20133 conversational questions",
      "Direct calendar booking into your PMS",
      "7\u201314 day ghosted-lead re-engagement sequence",
      "Real-time human handoff with full conversation context",
      "Per-campaign attribution and ROI reporting",
      "Spam and tire-kicker filtering before your team sees the lead"
    ],
    bestFor: [
      "Clinics spending $2K+/month on Google or Meta ads",
      "Practices running implant, Invisalign, or cosmetic ad campaigns",
      "DSOs with multiple locations and shared ad spend",
      "Any clinic where leads sit in an inbox for hours before reply"
    ],
    faqs: [
      {
        q: "What ad platforms do you support?",
        a: "Google Ads (Lead Forms, Search, Performance Max), Facebook & Instagram Lead Ads, Meta Messenger, TikTok Lead Generation, and any website form via webhook. Custom CRM integrations available."
      },
      {
        q: "Will the AI sound spammy or scare leads off?",
        a: "No. We A/B test message tone for every client and tune for the local market. The AI uses your clinic's name, references the specific ad the lead clicked on, and asks helpful questions \u2014 not pressure tactics."
      },
      {
        q: "What about TCPA / SMS compliance?",
        a: "Every message includes opt-out language, only goes to leads who consented on the ad form, and is sent from a registered 10DLC business number. Full compliance documentation is provided."
      },
      {
        q: "How fast do I see results?",
        a: "Booking rates typically double within the first 14 days. Re-engagement of ghosted leads compounds month-over-month \u2014 most clinics see steady-state ROI by day 60."
      }
    ],
    relatedSlugs: ["ai-receptionist", "treatment-followup"]
  },
  {
    slug: "treatment-followup",
    name: "AI Treatment Plan Follow-Up & Reactivation",
    shortName: "Treatment Plan Follow-Up",
    tagline: "Reactivate 15\u201325% of unaccepted treatment plans sitting in your PMS.",
    summary: "A done-for-you AI nurture system that follows up on every unaccepted dental treatment plan over a 30\u201360 day cadence \u2014 prioritizing high-value $3K+ cases and turning dormant production into booked revenue.",
    intro: "Every private dental practice has a six- or seven-figure pile of diagnosed-but-unaccepted treatment plans sitting in their PMS. Patients rarely say no outright \u2014 they say 'let me think about it,' 'I need to check with my spouse,' or 'I'll call you back.' Without a structured follow-up cadence, those plans quietly die. We reactivate them automatically.",
    outcomes: [
      { value: "15\u201325%", label: "Reactivation rate on stuck plans" },
      { value: "$3K+", label: "High-value cases prioritized first" },
      { value: "30\u201360d", label: "Full nurture cadence per patient" }
    ],
    howItWorks: [
      {
        title: "We pull your unaccepted plans",
        body: "We import every unaccepted treatment plan from Dentrix, Open Dental, Eaglesoft, or Curve, sort by treatment value, and prioritize $3K+ cases first."
      },
      {
        title: "Personalized 30\u201360 day cadence",
        body: "SMS + email referencing the specific procedure, with objection-handling content (cost, timing, fear) and one-tap booking links. No discounts or pressure \u2014 just helpful nudges."
      },
      {
        title: "Bookings, escalations, and reporting",
        body: "Booked appointments flow straight into your calendar. Clinical questions or callback requests escalate to your team. Monthly report shows every reactivated dollar."
      }
    ],
    features: [
      "Automated import of unaccepted treatment plans from your PMS",
      "30\u201360 day personalized SMS + email cadence",
      "Built-in objection handling: cost (financing), timing, fear/sedation",
      "$3K+ case prioritization (implants, ortho, full arches, large restorative)",
      "One-tap booking links into your calendar",
      "Human escalation for clinical questions or frustration",
      "Monthly reactivation report with dollar-tracked ROI"
    ],
    bestFor: [
      "Practices with 50+ unaccepted plans sitting in their PMS",
      "Implant, ortho, and cosmetic practices with high-ticket cases",
      "Clinics where no one has time for systematic follow-up",
      "Owners who want production from patients already diagnosed"
    ],
    faqs: [
      {
        q: "How far back do you reactivate plans?",
        a: "We typically import unaccepted plans from the last 18\u201324 months. Plans older than that get a softer re-introduction sequence; recent plans (under 90 days) get the full objection-handling cadence."
      },
      {
        q: "Will patients feel spammed?",
        a: "No. Each patient gets 6\u20138 touches over 60 days \u2014 not daily messages. Every message is personalized to their specific procedure and includes opt-out. Patients who decline are immediately removed from the sequence."
      },
      {
        q: "What's a realistic reactivation rate?",
        a: "15\u201325% of unaccepted plans book within 60 days across our installs. On a $200K backlog of unaccepted treatment, that's $30K\u2013$50K of recovered production in the first 2 months."
      },
      {
        q: "Do you offer discounts on behalf of the clinic?",
        a: "Only if you ask us to. By default, the sequence uses financing options (CareCredit, Sunbit, in-house plans) and education \u2014 never discounts. We've found discounting trains patients to wait."
      }
    ],
    relatedSlugs: ["ai-receptionist", "lead-response"]
  }
];

// src/data/integrations.ts
var integrations = [
  {
    slug: "dentrix",
    name: "Dentrix",
    vendor: "Henry Schein One",
    summary: "OrthoAutomate integrates directly with Dentrix to read appointments, write new bookings, and sync patient records \u2014 no rip-and-replace, no workflow change for your front desk.",
    description: "Dentrix is the most widely deployed practice-management system in U.S. private dentistry. Our AI receptionist, lead-response engine, and treatment-plan follow-up sequences all read and write directly to Dentrix via the official API, so every booked call, qualified ad lead, and reactivated treatment plan lands in your existing schedule and patient ledger automatically.",
    capabilities: [
      "Read live calendar availability and provider schedules",
      "Write new appointments with full patient details and insurance",
      "Sync patient records (new and existing) bi-directionally",
      "Import unaccepted treatment plans for AI follow-up sequencing",
      "Log every AI call transcript and SMS thread to the patient file",
      "Trigger workflows on appointment status changes (no-show, confirmed)"
    ],
    setupTimeline: "72 hours from kickoff \u2014 we handle 100% of the technical setup, including credentials, mapping, and front-desk onboarding."
  },
  {
    slug: "open-dental",
    name: "Open Dental",
    vendor: "Open Dental Software",
    summary: "Direct Open Dental API integration for live scheduling, patient records, and treatment-plan import \u2014 fully open-source friendly, no third-party middleware.",
    description: "Open Dental's open architecture and FHIR-aligned API make it our cleanest integration. The AI receptionist books appointments straight into the Open Dental schedule, lead response writes new patient records with full ad-source attribution, and treatment-plan follow-up imports unaccepted plans nightly for prioritized AI outreach.",
    capabilities: [
      "Real-time schedule reads and appointment writes via Open Dental API",
      "Full patient record sync (demographics, insurance, history)",
      "Automatic ad-source attribution on new-patient records",
      "Nightly unaccepted treatment-plan import for AI follow-up",
      "Operatory and provider-level routing for multi-doctor practices",
      "Call recording and SMS history attached to the patient chart"
    ],
    setupTimeline: "72 hours \u2014 we provision API access, map your operatories and providers, and onboard your team."
  },
  {
    slug: "eaglesoft",
    name: "Eaglesoft",
    vendor: "Patterson Dental",
    summary: "OrthoAutomate connects to Eaglesoft for live appointment booking, patient sync, and treatment-plan reactivation \u2014 works across single-location and multi-location practices.",
    description: "Eaglesoft powers a large share of U.S. general and specialty dental practices. Our integration uses Eaglesoft's supported data interfaces to book appointments, sync patient demographics and insurance, and pull unaccepted treatment plans for AI follow-up \u2014 without disrupting your team's day-to-day workflow.",
    capabilities: [
      "Live appointment booking with provider and operatory matching",
      "Patient demographic and insurance sync",
      "Unaccepted treatment-plan import for AI nurture cadences",
      "AI call transcripts logged to the patient record",
      "Multi-location support with per-site routing",
      "No on-site server changes \u2014 fully managed setup"
    ],
    setupTimeline: "72 hours \u2014 we coordinate with your Patterson rep when needed, then handle the rest."
  },
  {
    slug: "curve-dental",
    name: "Curve Dental",
    vendor: "Curve Dental",
    summary: "Cloud-native Curve Dental integration for instant appointment booking, patient sync, and treatment-plan reactivation \u2014 perfect for modern multi-location practices.",
    description: "Curve Dental's cloud-first architecture pairs naturally with our AI stack. Every booked call, qualified ad lead, and reactivated treatment plan flows in real time into Curve, with full ad-source and AI-conversation attribution attached to each patient record.",
    capabilities: [
      "Real-time cloud-to-cloud appointment booking",
      "Bi-directional patient record and insurance sync",
      "Treatment-plan import with value-based prioritization",
      "AI call recordings, transcripts, and SMS threads attached to chart",
      "Multi-location and provider-level scheduling support",
      "Ad-source attribution captured at lead creation"
    ],
    setupTimeline: "72 hours \u2014 fully cloud-based, no on-site setup required."
  }
];

// src/data/landingPages.ts
var landingPages = [
  // ─── USE CASES ──────────────────────────────────────────────────────────────
  {
    slug: "missed-call-recovery-for-dental-clinics",
    category: "use-case",
    breadcrumbLabel: "Missed Call Recovery",
    h1: "Missed Call Recovery for Dental Clinics",
    title: "Missed Call Recovery for Dental Clinics | OrthoAutomate AI Receptionist",
    metaDescription: "Stop losing $4K\u2013$12K/month to missed dental clinic calls. Our AI receptionist answers in under 2 seconds, books straight into Dentrix/Open Dental/Eaglesoft/Curve, and runs 24/7.",
    quickAnswer: {
      question: "How do dental clinics recover missed calls without hiring more staff?",
      answer: "OrthoAutomate installs a 24/7 AI receptionist that answers every dental clinic call in under 2 seconds, books appointments directly into Dentrix, Open Dental, Eaglesoft, or Curve, and routes urgent cases to a human. Clinics typically cut missed-call rates from 25%+ to under 3% and recover $4,000\u2013$12,000 in monthly production."
    },
    intro: "Most private dental practices miss 18\u201335% of inbound calls during huddles, lunch, after-hours, and weekends. Each missed new-patient call is worth $600\u2013$1,200 in first-visit production \u2014 and $4K\u2013$25K in lifetime value for ortho, implants, or full-arch cases. This page explains how an AI receptionist closes that gap permanently, without adding front-desk staff.",
    outcomes: [
      { value: "<2s", label: "Average pickup time" },
      { value: "<3%", label: "Missed-call rate post-install (typical)" },
      { value: "60\u201380%", label: "Recovered calls that book" }
    ],
    howItWorks: [
      {
        title: "Audit your missed-call leak",
        body: "We pull your last 30 days of call logs from your VoIP (RingCentral, Mango, Weave, etc.) and calculate the exact monthly dollar loss based on your average new-patient value."
      },
      {
        title: "Install the AI receptionist in 72 hours",
        body: "We train the AI on your services, hours, providers, insurance, and brand tone, then connect it directly to your PMS calendar and phone system. Zero work for your team."
      },
      {
        title: "Track every recovered call",
        body: "Monthly report shows calls captured, appointments booked, and dollars recovered \u2014 with transcripts logged into your PMS for review."
      }
    ],
    features: [
      "24/7/365 coverage \u2014 no voicemail, no missed calls",
      "Direct calendar booking into Dentrix, Open Dental, Eaglesoft, Curve",
      "Bilingual support (English + Spanish) on request",
      "Real-time human escalation with full conversation context",
      "Call recordings and transcripts logged to your PMS",
      "Custom voice + brand tone \u2014 sounds like your front desk",
      "Encrypted in transit and at rest"
    ],
    bestFor: [
      "Practices missing 15%+ of inbound calls",
      "Clinics overwhelmed at peak hours, lunch, and after-work spike",
      "Multi-location DSOs needing consistent call handling",
      "Specialty practices (ortho, implants, cosmetic) with high-value calls"
    ],
    faqs: [
      {
        q: "How much revenue does the average clinic recover from missed-call capture?",
        a: "Clinics with 20%+ missed-call rates typically recover $4,000\u2013$12,000/month in booked production after install. The exact figure depends on call volume, average new-patient value, and historical booking rate. Our free Revenue Audit calculates this from your actual call logs before you commit to anything."
      },
      {
        q: "How is this different from voicemail or a call-overflow service?",
        a: "Voicemail loses 80%+ of new-patient callers \u2014 they hang up and call a competitor. Generic overflow call centers don't know your providers, insurance, or pricing, and can't book into your PMS. Our AI receptionist books directly into your calendar, sounds like your front desk, and knows your clinic's services."
      },
      {
        q: "Can patients tell they're talking to AI?",
        a: "Most cannot. The AI uses natural conversational tone, handles interruptions, and adapts to accents. The moment a caller asks for a human or has an emergency, the call transfers instantly with full context."
      },
      {
        q: "What happens during a real dental emergency?",
        a: "The AI is trained on emergency keywords (swelling, severe pain, trauma, broken tooth) and routes the call immediately to your on-call number with the patient's name, callback number, and a one-line summary."
      },
      {
        q: "Which dental PMS do you integrate with?",
        a: "Direct integrations with Dentrix, Open Dental, Eaglesoft, and Curve Dental are included. CSV/manual workflows are supported as a fallback for less common systems."
      },
      {
        q: "How long does setup take?",
        a: "72 hours from kickoff. We handle 100% of the technical setup \u2014 phone routing, PMS integration, AI training on your clinic's tone and services, and team onboarding."
      },
      {
        q: "Is there a long-term contract?",
        a: "No. All plans are month-to-month and you can cancel any time. We earn the business each month through measurable recovered revenue."
      }
    ],
    internalLinks: [
      { label: "Calculate your missed-call revenue loss", to: "/roi-calculator" },
      { label: "Manual follow-up vs AI \u2014 full comparison", to: "/compare/manual-follow-up-vs-ai" },
      { label: "Treatment plan follow-up automation", to: "/treatment-plan-follow-up-ai" },
      { label: "How we handle data & privacy", to: "/security-and-privacy" }
    ],
    serviceType: "Missed Call Recovery for Dental Clinics"
  },
  {
    slug: "treatment-plan-follow-up-ai",
    category: "use-case",
    breadcrumbLabel: "Treatment Plan Follow-Up",
    h1: "AI Treatment Plan Follow-Up for Dental Clinics",
    title: "AI Treatment Plan Follow-Up for Dental Clinics | OrthoAutomate",
    metaDescription: "Reactivate 15\u201325% of unaccepted dental treatment plans. AI nurture sequences over 30\u201360 days, prioritizing $3K+ cases. Works with Dentrix, Open Dental, Eaglesoft, Curve.",
    quickAnswer: {
      question: "How do you follow up on unaccepted dental treatment plans automatically?",
      answer: "OrthoAutomate imports every unaccepted treatment plan from your PMS, prioritizes $3K+ cases, and runs personalized 30\u201360 day SMS and email sequences with objection-handling content and one-tap booking links. Across installs, 15\u201325% of stuck plans reactivate without discounts or pressure tactics."
    },
    intro: "Every private dental practice has a six- or seven-figure pile of diagnosed-but-unaccepted treatment plans sitting in their PMS. Patients rarely say no outright \u2014 they say 'let me think,' 'I'll check with my spouse,' or 'I'll call back.' Without a structured follow-up cadence, those plans quietly die. This page explains the framework we use to reactivate them.",
    outcomes: [
      { value: "15\u201325%", label: "Reactivation rate on stuck plans (typical)" },
      { value: "$3K+", label: "High-value cases prioritized first" },
      { value: "30\u201360 days", label: "Full nurture cadence per patient" }
    ],
    howItWorks: [
      {
        title: "Import unaccepted plans",
        body: "We pull every unaccepted treatment plan from the last 18\u201324 months out of Dentrix, Open Dental, Eaglesoft, Curve, or a CSV export, then sort by treatment value."
      },
      {
        title: "Run the 30\u201360 day cadence",
        body: "Personalized SMS + email referencing the specific procedure, with objection handling for cost (financing), timing, and fear/sedation. One-tap booking links throughout."
      },
      {
        title: "Book, escalate, and report",
        body: "Booked appointments flow straight into your calendar. Clinical questions or frustration escalate to your team. Monthly report shows every reactivated dollar."
      }
    ],
    features: [
      "Automated import of unaccepted plans from your PMS",
      "30\u201360 day SMS + email cadence with objection handling",
      "$3K+ case prioritization (implants, ortho, full arches, large restorative)",
      "One-tap booking links into your calendar",
      "Human escalation for clinical questions or frustration",
      "Monthly reactivation report with dollar-tracked ROI",
      "Opt-out on every message"
    ],
    bestFor: [
      "Practices with 50+ unaccepted plans sitting in the PMS",
      "Implant, ortho, and cosmetic practices with high-ticket cases",
      "Clinics where no one has time for systematic follow-up",
      "Owners who want production from patients already diagnosed"
    ],
    faqs: [
      {
        q: "How far back do you reactivate plans?",
        a: "We typically import unaccepted plans from the last 18\u201324 months. Plans older than that get a softer re-introduction sequence; plans under 90 days old get the full objection-handling cadence."
      },
      {
        q: "Will patients feel spammed?",
        a: "No. Patients get 6\u20138 touches over 60 days \u2014 not daily messages. Every message is personalized to the specific procedure and includes opt-out. Patients who decline are removed immediately."
      },
      {
        q: "What's a realistic reactivation rate?",
        a: "15\u201325% of unaccepted plans book within 60 days across our installs. On a $200K backlog of stuck treatment, that's $30K\u2013$50K of recovered production in the first 2 months."
      },
      {
        q: "Do you offer discounts to close the case?",
        a: "Only if you ask us to. By default the sequence uses financing options (CareCredit, Sunbit, in-house plans) and patient education \u2014 never discounts. Discounting trains patients to wait."
      },
      {
        q: "Which PMS systems do you support?",
        a: "Dentrix, Open Dental, Eaglesoft, and Curve Dental directly. CSV exports work for any other system as a fallback."
      },
      {
        q: "Is patient data handled securely?",
        a: "Yes \u2014 encrypted in transit and at rest, minimum-necessary data principle, and patient information is never used to train public AI models. See our Security & Privacy page for details."
      },
      {
        q: "How is success measured?",
        a: "Booked appointments and dollars of treatment reactivated \u2014 both reported monthly, tied to specific patients and procedures so you can verify against your PMS."
      }
    ],
    internalLinks: [
      { label: "Estimate reactivation revenue", to: "/roi-calculator" },
      { label: "How AI follows up treatment plans", to: "/blog/how-ai-follows-up-treatment-plans" },
      { label: "Manual follow-up vs AI", to: "/compare/manual-follow-up-vs-ai" },
      { label: "Dental lead conversion automation", to: "/dental-lead-conversion-ai" }
    ],
    serviceType: "AI Treatment Plan Follow-Up"
  },
  {
    slug: "dental-lead-conversion-ai",
    category: "use-case",
    breadcrumbLabel: "Dental Lead Conversion",
    h1: "AI Dental Lead Conversion \u2014 Reply to Every Ad Lead in Under 60 Seconds",
    title: "AI Dental Lead Conversion | OrthoAutomate (Google, Facebook, Instagram)",
    metaDescription: "Reply to every Google, Facebook, and Instagram dental ad lead in under 60 seconds via SMS and DM. Qualify, book, and re-engage ghosted leads automatically.",
    quickAnswer: {
      question: "How do dental clinics convert more Google and Facebook ad leads?",
      answer: "OrthoAutomate replies to every paid ad lead in under 60 seconds via SMS and Instagram/Facebook DM, qualifies them with 2\u20133 conversational questions, and books directly into the clinic's calendar. Ghosted leads get a 7\u201314 day re-engagement sequence. Booking rates typically double without changing ad spend."
    },
    intro: "Industry research is unambiguous: leads contacted within 5 minutes are roughly 100\xD7 more likely to qualify than those contacted after 30 minutes. Most dental clinics take hours \u2014 sometimes days \u2014 to reply, while a competitor's auto-responder is already in the conversation. This page explains how we close that gap to under 60 seconds.",
    outcomes: [
      { value: "<60s", label: "Average response time" },
      { value: "~2\xD7", label: "Booking rate vs. human-only (typical)" },
      { value: "~50%", label: "Lower effective cost per booked patient" }
    ],
    howItWorks: [
      {
        title: "Connect your lead sources",
        body: "Direct integrations with Google Ads Lead Forms, Facebook & Instagram Lead Ads, Meta Messenger, website forms, and your CRM. Every new lead hits the AI in real time."
      },
      {
        title: "Qualify in 2\u20133 messages",
        body: "Conversational SMS / DM that confirms service interest, insurance, location, and preferred time \u2014 without sounding like a survey."
      },
      {
        title: "Book or re-engage",
        body: "Qualified leads are booked directly into the calendar. Ghosted leads get a 7\u201314 day sequence that typically recovers 20\u201330% of them."
      }
    ],
    features: [
      "<60-second reply across SMS, Instagram DM, Facebook Messenger",
      "Direct calendar booking into your PMS",
      "7\u201314 day ghosted-lead re-engagement sequence",
      "Real-time human handoff with full conversation context",
      "Per-campaign attribution and ROI reporting",
      "Spam/tire-kicker filtering before your team sees the lead",
      "TCPA / 10DLC-compliant SMS infrastructure"
    ],
    bestFor: [
      "Clinics spending $2K+/month on Google or Meta ads",
      "Practices running implant, Invisalign, or cosmetic campaigns",
      "DSOs with multiple locations and shared ad spend",
      "Any clinic where leads sit in an inbox for hours"
    ],
    faqs: [
      {
        q: "Which ad platforms do you support?",
        a: "Google Ads (Lead Forms, Search, Performance Max), Facebook & Instagram Lead Ads, Meta Messenger, TikTok Lead Generation, and any website form via webhook. Custom CRM integrations are available."
      },
      {
        q: "Will the AI sound spammy and scare leads off?",
        a: "No. We A/B test message tone for every clinic and tune for the local market. The AI uses your clinic's name, references the specific ad the lead clicked, and asks helpful questions \u2014 not pressure tactics."
      },
      {
        q: "What about TCPA / SMS compliance?",
        a: "Every message includes opt-out language, only goes to leads who consented on the ad form, and is sent from a registered 10DLC business number. Full compliance documentation is provided."
      },
      {
        q: "How fast do I see results?",
        a: "Booking rates typically double within 14 days. Re-engagement of ghosted leads compounds month-over-month \u2014 most clinics see steady-state ROI by day 60."
      },
      {
        q: "Does this replace my marketing agency?",
        a: "No \u2014 it makes them more effective. Your agency drives the lead; we make sure the lead actually becomes a booked appointment. Most agencies see their reported CPA drop 30\u201350% after install."
      },
      {
        q: "Can the AI handle insurance questions?",
        a: "Yes. It's trained on which insurance plans your clinic accepts, in-network vs out-of-network policies, and self-pay financing options. Edge cases escalate to a human."
      }
    ],
    internalLinks: [
      { label: "Why 60-second lead response doubles ad ROI", to: "/blog/ad-lead-response-time-dental-marketing" },
      { label: "Estimate lead conversion revenue", to: "/roi-calculator" },
      { label: "Missed call recovery", to: "/missed-call-recovery-for-dental-clinics" },
      { label: "No-show recovery automation", to: "/no-show-recovery-automation" }
    ],
    serviceType: "AI Dental Lead Conversion"
  },
  {
    slug: "no-show-recovery-automation",
    category: "use-case",
    breadcrumbLabel: "No-Show Recovery",
    h1: "Dental No-Show Recovery Automation",
    title: "Dental No-Show Recovery Automation | OrthoAutomate",
    metaDescription: "Automatically recover dental no-shows and last-minute cancellations. AI confirms, reschedules, and fills holes in the schedule using your existing PMS.",
    quickAnswer: {
      question: "How can dental clinics reduce no-shows and recover empty chair time?",
      answer: "OrthoAutomate runs AI confirmation sequences before every appointment and, when no-shows or cancellations happen, automatically reaches out to reschedule and fills open chair time from a prioritized waitlist of dormant and treatment-plan patients. Clinics typically cut no-show rates 30\u201350% and recover 2\u20135 chair-hours per week."
    },
    intro: "A typical no-show in general dentistry costs $250\u2013$400 in lost chair time; in specialty practices it's $800\u2013$2,500. Most clinics have no system for backfilling that time \u2014 the chair just sits empty. This page explains how AI confirms, recovers, and refills no-shows automatically.",
    outcomes: [
      { value: "30\u201350%", label: "No-show rate reduction (typical)" },
      { value: "2\u20135 hrs", label: "Chair-time refilled per week" },
      { value: "24/7", label: "Automatic confirmations + recovery" }
    ],
    howItWorks: [
      {
        title: "Pre-appointment confirmations",
        body: "AI sends SMS confirmations 72h, 24h, and 2h before each appointment with one-tap confirm / reschedule. Patients who don't confirm escalate to a final personal touch."
      },
      {
        title: "Instant no-show recovery",
        body: "When a no-show happens, AI immediately reaches the patient to reschedule with empathy \u2014 not a generic blast. Reasons (forgot, transport, anxiety) feed future workflows."
      },
      {
        title: "Backfill from a smart waitlist",
        body: "Open chair time is offered to a ranked waitlist (treatment-plan patients, dormant high-LTV patients, hygiene overdue) so the slot rarely stays empty."
      }
    ],
    features: [
      "Multi-touch SMS confirmations with one-tap actions",
      "Automatic rescheduling on no-show / cancellation",
      "Smart waitlist prioritizing high-value patients",
      "PMS integration: Dentrix, Open Dental, Eaglesoft, Curve",
      "Reason-code tracking (forgot, transport, anxiety, cost)",
      "Human escalation when sentiment turns negative",
      "Monthly report on recovered chair-hours and production"
    ],
    bestFor: [
      "Practices with no-show rates above 8%",
      "Specialty clinics where empty chair time is $800+/hour",
      "Multi-provider practices with complex schedules",
      "Clinics already running treatment-plan follow-up who want full schedule density"
    ],
    faqs: [
      {
        q: "How much does a no-show actually cost?",
        a: "In general dentistry, $250\u2013$400 per slot. In ortho, implants, or cosmetic specialties, $800\u2013$2,500 per slot. A practice losing 6 hours/week to no-shows is leaving $60K\u2013$300K per year on the table."
      },
      {
        q: "Will patients find confirmation messages annoying?",
        a: "No \u2014 most patients prefer SMS confirmations to phone calls. Frequency is tuned per clinic; patients can opt down to a single 24h reminder if they prefer."
      },
      {
        q: "How does the waitlist know who to call first?",
        a: "Patients are ranked by treatment value, recency, opt-in status, and likelihood to accept based on past behavior. High-LTV patients with active treatment plans are always offered first."
      },
      {
        q: "Does this work with HIPAA / privacy rules?",
        a: "Yes. Messages reveal only minimum-necessary information (appointment time, clinic name) and patient data stays inside the secure pipeline. We don't claim formal HIPAA certification \u2014 see our Security & Privacy page for full detail."
      },
      {
        q: "How fast can we see no-show rates drop?",
        a: "Most clinics see a measurable drop in 2\u20133 weeks once full confirmation coverage starts. The backfill side compounds month-over-month as the waitlist matures."
      },
      {
        q: "Can it handle same-day cancellations?",
        a: "Yes \u2014 same-day cancellations trigger instant waitlist outreach to high-priority patients within minutes, often filling the slot before the original patient even notices the rescheduling."
      }
    ],
    internalLinks: [
      { label: "Dormant patient reactivation", to: "/dormant-patient-reactivation" },
      { label: "Treatment plan follow-up", to: "/treatment-plan-follow-up-ai" },
      { label: "ROI calculator", to: "/roi-calculator" },
      { label: "Security and privacy", to: "/security-and-privacy" }
    ],
    serviceType: "Dental No-Show Recovery Automation"
  },
  {
    slug: "dormant-patient-reactivation",
    category: "use-case",
    breadcrumbLabel: "Dormant Patient Reactivation",
    h1: "Dormant Dental Patient Reactivation",
    title: "Dormant Patient Reactivation for Dental Clinics | OrthoAutomate",
    metaDescription: "Reactivate patients who haven't been seen in 12+ months. AI personalized re-engagement using your PMS history \u2014 recover hygiene, perio, and overdue treatment.",
    quickAnswer: {
      question: "How do dental clinics bring back patients who haven't been seen in over a year?",
      answer: "OrthoAutomate pulls dormant patients (typically 12+ months since last visit) from your PMS, segments them by last procedure and lifetime value, and runs personalized SMS + email re-engagement that books overdue hygiene, perio maintenance, and outstanding treatment. Reactivation rates of 8\u201315% are typical in the first 90 days."
    },
    intro: "Every dental practice has a long tail of patients who 'fell off the chart' \u2014 moved jobs, lost insurance, missed a recall, or just drifted away. They were already comfortable with your team; reactivating them is faster and cheaper than acquiring a new patient. This page explains how we do it automatically.",
    outcomes: [
      { value: "8\u201315%", label: "Dormant-patient reactivation in 90 days" },
      { value: "12+ mo", label: "Default dormancy window" },
      { value: "1/5 cost", label: "Vs. acquiring a new patient via ads" }
    ],
    howItWorks: [
      {
        title: "Segment the dormant list",
        body: "Pull patients from your PMS by last-visit date and segment by last procedure, lifetime value, and overdue recall \u2014 so the right message reaches the right patient."
      },
      {
        title: "Personalized re-engagement",
        body: "SMS + email that references the specific recall or treatment they're due for, with one-tap booking. Tone is warm, not transactional."
      },
      {
        title: "Compound monthly",
        body: "Reactivated patients re-enter normal hygiene recall and treatment-plan follow-up \u2014 so they don't drift away again. Monthly report shows reactivations + downstream production."
      }
    ],
    features: [
      "PMS-driven dormant patient segmentation",
      "Personalized SMS + email re-engagement",
      "One-tap booking into your calendar",
      "Insurance / benefit reset reminders (calendar-year prompts)",
      "Hand-off to live front desk for complex requests",
      "Monthly report showing reactivated patients + production",
      "Patient suppression list respected (opt-outs, deceased, transferred)"
    ],
    bestFor: [
      "Practices with 500+ dormant patients in the PMS",
      "Clinics whose hygiene chair has unused capacity",
      "Owners who want to use their existing patient base before scaling ad spend",
      "Specialty practices where past patients still need recall/maintenance"
    ],
    faqs: [
      {
        q: "What counts as a 'dormant' patient?",
        a: "By default, any active patient with no completed visit in the last 12+ months. The window is configurable per clinic \u2014 some prefer 6 months for hygiene, 18 for treatment."
      },
      {
        q: "Won't patients feel like I'm just hounding them?",
        a: "No. The cadence is warm and limited (typically 3\u20134 touches over 6 weeks), opt-out is on every message, and patients who don't engage stop receiving messages."
      },
      {
        q: "How is this different from a generic recall campaign?",
        a: "Generic recalls send the same message to everyone. Our system personalizes per patient \u2014 last procedure, last provider, overdue recall, and remaining insurance benefits \u2014 so the message actually matters."
      },
      {
        q: "What about patients who moved or transferred?",
        a: "Bounced numbers, unresponsive patients across multiple cycles, and explicit transfer/move signals automatically suppress that patient from future sequences."
      },
      {
        q: "How does this stack with treatment-plan follow-up?",
        a: "Treatment-plan follow-up handles diagnosed-but-unaccepted cases. Dormant reactivation handles patients we've lost contact with. Together they cover the full inactive base."
      },
      {
        q: "How quickly do I see reactivations?",
        a: "First booked reactivations typically land within the first 7\u201310 days. Steady-state production from this channel usually shows up in monthly reports by day 60."
      }
    ],
    internalLinks: [
      { label: "Treatment plan follow-up", to: "/treatment-plan-follow-up-ai" },
      { label: "No-show recovery", to: "/no-show-recovery-automation" },
      { label: "ROI calculator", to: "/roi-calculator" },
      { label: "Security & privacy", to: "/security-and-privacy" }
    ],
    serviceType: "Dormant Patient Reactivation"
  },
  // ─── INTEGRATIONS ──────────────────────────────────────────────────────────
  {
    slug: "dentrix-ai-revenue-recovery",
    category: "integration",
    breadcrumbLabel: "Dentrix AI Revenue Recovery",
    h1: "Dentrix AI Revenue Recovery",
    title: "Dentrix AI Revenue Recovery | OrthoAutomate Integration",
    metaDescription: "AI revenue recovery for clinics running Dentrix. Capture missed calls, reactivate treatment plans, convert leads \u2014 booked directly into your Dentrix calendar.",
    quickAnswer: {
      question: "How does OrthoAutomate work with Dentrix?",
      answer: "OrthoAutomate connects directly to your Dentrix calendar and patient records to power three AI systems: a 24/7 missed-call receptionist that books straight into Dentrix, treatment-plan follow-up that pulls unaccepted plans from Dentrix Treatment Manager, and lead conversion that schedules new patients into open Dentrix slots \u2014 without changing your daily workflow."
    },
    intro: "Dentrix is the backbone of thousands of US dental practices. This page explains exactly how OrthoAutomate integrates with Dentrix to install missed-call recovery, treatment-plan follow-up, and lead conversion \u2014 with zero workflow disruption for your front desk.",
    outcomes: [
      { value: "72 hrs", label: "Setup to live on Dentrix" },
      { value: "0 changes", label: "To your Dentrix workflow" },
      { value: "Native", label: "Calendar + patient-record sync" }
    ],
    howItWorks: [
      {
        title: "Connect to Dentrix",
        body: "We connect to your Dentrix install via supported integration paths (eSync / API bridge / CSV fallback if needed). All work is done by our team \u2014 your IT or office manager doesn't have to lift a finger."
      },
      {
        title: "Sync calendar & treatment plans",
        body: "Two-way sync of the appointment book and read access to unaccepted treatment plans. The AI books into the same slots your team books into."
      },
      {
        title: "Go live in 72 hours",
        body: "Phone routing, lead sources, and follow-up sequences all activate together. Your front desk keeps using Dentrix exactly as they do today."
      }
    ],
    features: [
      "Direct Dentrix calendar booking",
      "Unaccepted treatment plan import from Treatment Manager",
      "Patient-record sync (notes, recall types, insurance)",
      "Multi-provider, multi-operatory scheduling support",
      "Works with Dentrix Ascend and Dentrix G7",
      "CSV/manual fallback for unsupported configurations"
    ],
    bestFor: [
      "Single and multi-location Dentrix practices",
      "Specialty clinics using Dentrix for ortho/implants/cosmetic",
      "DSOs standardized on Dentrix across locations"
    ],
    faqs: [
      {
        q: "Which versions of Dentrix do you support?",
        a: "Dentrix G6, G7, and Dentrix Ascend are supported via documented integration paths. Older versions or custom configurations are supported via CSV/manual workflows as a fallback."
      },
      {
        q: "Do you require a server or local install?",
        a: "No on-clinic install is required for the cloud workflows. For some on-prem Dentrix setups, a lightweight read/write bridge is installed during onboarding \u2014 we handle it."
      },
      {
        q: "What data does OrthoAutomate pull from Dentrix?",
        a: "Minimum-necessary: appointment book availability, patient contact info, recall status, and unaccepted treatment plans. We do not pull clinical chart notes or imaging."
      },
      {
        q: "Will this slow Dentrix down?",
        a: "No. All sync happens out-of-band and is throttled to avoid any impact on your live Dentrix usage."
      },
      {
        q: "What happens if our Dentrix server is down?",
        a: "The AI receptionist keeps answering calls. Bookings queue and sync when Dentrix is back online; your front desk sees no gaps in the schedule."
      },
      {
        q: "How long does setup take?",
        a: "72 hours from kickoff to live, including Dentrix integration, AI training on your clinic, and team onboarding."
      }
    ],
    internalLinks: [
      { label: "Open Dental integration", to: "/open-dental-ai-revenue-recovery" },
      { label: "Missed call recovery", to: "/missed-call-recovery-for-dental-clinics" },
      { label: "Treatment plan follow-up", to: "/treatment-plan-follow-up-ai" },
      { label: "Security & privacy", to: "/security-and-privacy" }
    ],
    serviceType: "Dentrix AI Revenue Recovery"
  },
  {
    slug: "open-dental-ai-revenue-recovery",
    category: "integration",
    breadcrumbLabel: "Open Dental AI Revenue Recovery",
    h1: "Open Dental AI Revenue Recovery",
    title: "Open Dental AI Revenue Recovery | OrthoAutomate Integration",
    metaDescription: "AI revenue recovery for Open Dental practices. Books straight into your Open Dental calendar via the official API. Missed calls, treatment plans, lead conversion.",
    quickAnswer: {
      question: "How does OrthoAutomate integrate with Open Dental?",
      answer: "OrthoAutomate uses Open Dental's official API to read appointments, unaccepted treatment plans, and patient records, and to write new bookings directly into your Open Dental calendar. The AI receptionist, treatment-plan follow-up, and lead conversion all run natively against your Open Dental database in 72 hours."
    },
    intro: "Open Dental's open API makes it one of the cleanest integrations in dental software. This page explains how OrthoAutomate uses that API to install missed-call recovery, treatment-plan follow-up, and lead conversion against your Open Dental system.",
    outcomes: [
      { value: "Native API", label: "Direct Open Dental integration" },
      { value: "72 hrs", label: "Setup to live" },
      { value: "Two-way", label: "Calendar + patient sync" }
    ],
    howItWorks: [
      {
        title: "Connect via the Open Dental API",
        body: "We configure the official Open Dental API connection during onboarding. Authentication uses a scoped key your team controls."
      },
      {
        title: "Sync schedule, patients, and plans",
        body: "Real-time read of appointments, patients, and unaccepted treatment plans. Write access scoped to booking new appointments."
      },
      {
        title: "Go live in 72 hours",
        body: "Phone routing, lead sources, and follow-up sequences activate together. Your front desk keeps using Open Dental exactly as today."
      }
    ],
    features: [
      "Official Open Dental API integration",
      "Direct calendar booking into the right operatory and provider",
      "Unaccepted treatment plan extraction with value sorting",
      "Recall/hygiene status sync for dormant patient reactivation",
      "Per-provider scheduling rules respected",
      "Self-hosted and cloud-hosted Open Dental supported"
    ],
    bestFor: [
      "Practices that picked Open Dental for openness and customization",
      "Multi-provider clinics with complex scheduling rules",
      "DSOs running Open Dental across locations"
    ],
    faqs: [
      {
        q: "Do you use the official Open Dental API?",
        a: "Yes. We integrate via Open Dental's official API \u2014 no screen-scraping, no unsupported hacks. Authentication and scopes are controlled by your team."
      },
      {
        q: "Self-hosted or cloud-hosted \u2014 does it matter?",
        a: "Both are supported. Self-hosted clinics need to whitelist our connection during onboarding; we handle the rest."
      },
      {
        q: "What about custom Open Dental setups?",
        a: "Custom operatory layouts, provider rules, and recall configurations are mapped during onboarding so the AI books into the right slot every time."
      },
      {
        q: "Does the AI honor my appointment-type rules?",
        a: "Yes \u2014 appointment types, durations, and provider restrictions in Open Dental are respected. The AI never books into a slot your team wouldn't book into."
      },
      {
        q: "Can I see exactly what the AI changes in Open Dental?",
        a: "Yes. Every booking, every cancellation, every reschedule is logged with timestamps. You can audit it inside Open Dental and in our monthly report."
      },
      {
        q: "What if I switch from Open Dental later?",
        a: "All your patient communication history stays portable. If you migrate to Dentrix, Eaglesoft, or Curve, we re-point the integration during onboarding \u2014 no data loss."
      }
    ],
    internalLinks: [
      { label: "Dentrix integration", to: "/dentrix-ai-revenue-recovery" },
      { label: "Eaglesoft integration", to: "/eaglesoft-ai-revenue-recovery" },
      { label: "Treatment plan follow-up", to: "/treatment-plan-follow-up-ai" },
      { label: "ROI calculator", to: "/roi-calculator" }
    ],
    serviceType: "Open Dental AI Revenue Recovery"
  },
  {
    slug: "eaglesoft-ai-revenue-recovery",
    category: "integration",
    breadcrumbLabel: "Eaglesoft AI Revenue Recovery",
    h1: "Eaglesoft AI Revenue Recovery",
    title: "Eaglesoft AI Revenue Recovery | OrthoAutomate Integration",
    metaDescription: "AI revenue recovery for Eaglesoft clinics. Capture missed calls, follow up unaccepted treatment plans, and convert leads \u2014 booked directly into Eaglesoft.",
    quickAnswer: {
      question: "How does OrthoAutomate work with Eaglesoft?",
      answer: "OrthoAutomate connects to Eaglesoft via supported integration paths to read your appointment book, unaccepted treatment plans, and patient records, and to book new appointments back into Eaglesoft. The full stack \u2014 AI receptionist, treatment-plan follow-up, and lead conversion \u2014 runs against Eaglesoft in 72 hours."
    },
    intro: "Eaglesoft is the standard at thousands of Patterson Dental practices. This page explains how OrthoAutomate integrates with Eaglesoft to install missed-call recovery, treatment-plan follow-up, and lead conversion \u2014 without changing how your team uses Eaglesoft.",
    outcomes: [
      { value: "72 hrs", label: "Setup to live on Eaglesoft" },
      { value: "Native", label: "Calendar + patient sync" },
      { value: "0 retraining", label: "For your front desk" }
    ],
    howItWorks: [
      {
        title: "Connect to Eaglesoft",
        body: "We configure the Eaglesoft integration via supported integration partners or a secure local bridge. Done entirely by our team."
      },
      {
        title: "Sync calendar, patients, plans",
        body: "Real-time read of the appointment book and unaccepted treatment plans. The AI books directly into the same Eaglesoft schedule your team uses."
      },
      {
        title: "Go live in 72 hours",
        body: "AI receptionist, treatment-plan follow-up, and lead conversion all activate together. Your team keeps using Eaglesoft exactly as today."
      }
    ],
    features: [
      "Direct Eaglesoft calendar booking",
      "Unaccepted treatment plan extraction",
      "Patient-record sync (recall, insurance, contact)",
      "Multi-provider scheduling support",
      "Local-server-friendly bridge architecture",
      "CSV/manual fallback for edge cases"
    ],
    bestFor: [
      "Patterson Dental / Eaglesoft practices, single or multi-location",
      "Specialty clinics running Eaglesoft for orthodontics or cosmetic",
      "Owners who don't want to migrate PMS just to get AI"
    ],
    faqs: [
      {
        q: "Do I need to install anything on our Eaglesoft server?",
        a: "Most setups use a lightweight, read-and-write bridge installed by our team during onboarding. The bridge respects your network and IT policies."
      },
      {
        q: "Does Patterson need to be involved?",
        a: "Usually not. The bridge runs alongside Eaglesoft without modifying it. If your Patterson rep needs to whitelist anything, we provide the documentation."
      },
      {
        q: "What data is pulled from Eaglesoft?",
        a: "Minimum-necessary: appointment availability, patient contact info, recall status, and unaccepted treatment plans. We do not access clinical charting or imaging."
      },
      {
        q: "What happens if Eaglesoft is offline?",
        a: "The AI receptionist keeps answering and queues new bookings. They sync back to Eaglesoft the moment the system is reachable \u2014 no lost appointments."
      },
      {
        q: "Will the AI overbook?",
        a: "No. The AI sees real-time availability before offering a slot, and respects provider/operatory rules configured in Eaglesoft."
      },
      {
        q: "How long does setup take?",
        a: "72 hours from kickoff. We handle Eaglesoft integration, AI training, phone routing, and team onboarding."
      }
    ],
    internalLinks: [
      { label: "Dentrix integration", to: "/dentrix-ai-revenue-recovery" },
      { label: "Curve Dental integration", to: "/curve-dental-ai-revenue-recovery" },
      { label: "Missed call recovery", to: "/missed-call-recovery-for-dental-clinics" },
      { label: "Security & privacy", to: "/security-and-privacy" }
    ],
    serviceType: "Eaglesoft AI Revenue Recovery"
  },
  {
    slug: "curve-dental-ai-revenue-recovery",
    category: "integration",
    breadcrumbLabel: "Curve Dental AI Revenue Recovery",
    h1: "Curve Dental AI Revenue Recovery",
    title: "Curve Dental AI Revenue Recovery | OrthoAutomate Integration",
    metaDescription: "Cloud-native AI revenue recovery for Curve Dental clinics. Real-time calendar booking, treatment plan follow-up, and lead conversion via Curve's modern API.",
    quickAnswer: {
      question: "How does OrthoAutomate integrate with Curve Dental?",
      answer: "OrthoAutomate connects to Curve Dental's cloud platform to book appointments directly into Curve, pull unaccepted treatment plans, and sync patient records in real time. Because Curve is cloud-native, integration is fast \u2014 the AI receptionist, treatment-plan follow-up, and lead conversion all go live in 72 hours."
    },
    intro: "Curve Dental is the leading modern cloud PMS in dentistry. This page explains how OrthoAutomate integrates with Curve to install missed-call recovery, treatment-plan follow-up, and lead conversion \u2014 taking full advantage of Curve's cloud-native architecture.",
    outcomes: [
      { value: "Cloud-native", label: "No local install required" },
      { value: "Real-time", label: "Two-way calendar sync" },
      { value: "72 hrs", label: "Live on Curve" }
    ],
    howItWorks: [
      {
        title: "Connect to Curve Dental",
        body: "We configure the Curve integration via supported pathways during onboarding. No on-site install \u2014 everything runs cloud-to-cloud."
      },
      {
        title: "Sync schedule, patients, plans",
        body: "Real-time read of appointments and unaccepted treatment plans, with scoped write access for new bookings."
      },
      {
        title: "Go live in 72 hours",
        body: "Phone routing, ad lead sources, and follow-up sequences activate together. Your team keeps using Curve exactly as today."
      }
    ],
    features: [
      "Cloud-native integration \u2014 no servers or bridges",
      "Real-time two-way calendar sync",
      "Unaccepted treatment plan extraction",
      "Multi-location support for Curve DSOs",
      "Recall/hygiene status sync",
      "Per-provider scheduling rules respected"
    ],
    bestFor: [
      "Cloud-first practices that picked Curve for modern UX",
      "Multi-location groups standardized on Curve",
      "Specialty practices that want zero-server-overhead AI"
    ],
    faqs: [
      {
        q: "Do I need to install anything?",
        a: "No. Curve is cloud, OrthoAutomate is cloud \u2014 integration is entirely server-to-server. Nothing runs on your office computers."
      },
      {
        q: "Does my Curve account need to be on a specific plan?",
        a: "Most current Curve plans expose the integration paths we use. If anything additional is needed, we'll flag it during the free audit before you commit."
      },
      {
        q: "How fast can we go live?",
        a: "Because Curve is cloud-native, integration is typically the fastest of any PMS \u2014 clinics usually go live within 72 hours of kickoff."
      },
      {
        q: "What about multi-location Curve setups?",
        a: "Fully supported. Each location can have its own AI receptionist persona, phone number, and reporting \u2014 while sharing centralized treatment-plan follow-up if desired."
      },
      {
        q: "What if Curve is down?",
        a: "The AI receptionist keeps answering. Bookings queue and sync back to Curve when it's reachable \u2014 your front desk sees no gaps."
      },
      {
        q: "Will the AI honor Curve's appointment rules?",
        a: "Yes \u2014 appointment types, durations, providers, and operatory restrictions are all respected. The AI never books a slot your team wouldn't book."
      }
    ],
    internalLinks: [
      { label: "Open Dental integration", to: "/open-dental-ai-revenue-recovery" },
      { label: "Eaglesoft integration", to: "/eaglesoft-ai-revenue-recovery" },
      { label: "Dental lead conversion", to: "/dental-lead-conversion-ai" },
      { label: "ROI calculator", to: "/roi-calculator" }
    ],
    serviceType: "Curve Dental AI Revenue Recovery"
  }
];

// src/lib/links.ts
var CALENDLY_URL = "https://calendly.com/orthoautomate/30min";

// src/lib/mcp/tools/get-company-info.ts
var SITE = "https://orthoautomate.online";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Get OrthoAutomate's public company facts: what it does, who it serves, founder, service and page map, and how to book a call. Good starting point for any question about the business.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "OrthoAutomate",
      website: SITE,
      summary: "OrthoAutomate builds AI revenue-recovery systems for private dental and orthodontic clinics \u2014 a 24/7 AI receptionist, instant new-lead response, and automated treatment-plan follow-up that plug into the clinic's existing practice-management software.",
      founder: "Jashim Uddin, Founder & CEO",
      whoWeServe: "Private dental, orthodontic, implant and cosmetic clinics \u2014 single-location and multi-location groups \u2014 that lose revenue to missed calls, slow lead response, unaccepted treatment plans, no-shows and dormant patients.",
      promisedOutcome: "Recover more booked appointments and reduce revenue leakage without changing the software or workflow the front desk already uses.",
      operatesIn: "Worldwide (English and Arabic support)",
      setupTime: "Typically 72 hours from kickoff, fully managed setup.",
      bookACallUrl: CALENDLY_URL,
      services: services.map((s) => ({
        slug: s.slug,
        name: s.name,
        url: `${SITE}/services/${s.slug}`
      })),
      integrations: integrations.map((i) => ({
        slug: i.slug,
        name: i.name,
        url: `${SITE}/integrations/${i.slug}`
      })),
      landingPages: landingPages.map((p) => ({
        slug: p.slug,
        category: p.category,
        label: p.breadcrumbLabel,
        url: `${SITE}/${p.slug}`
      })),
      keyPages: [
        `${SITE}/`,
        `${SITE}/about`,
        `${SITE}/services`,
        `${SITE}/integrations`,
        `${SITE}/pricing`,
        `${SITE}/case-studies`,
        `${SITE}/roi-calculator`,
        `${SITE}/faq`,
        `${SITE}/blog`,
        `${SITE}/contact`,
        `${SITE}/security-and-privacy`
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var SITE2 = "https://orthoautomate.online";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List every OrthoAutomate service (AI receptionist, instant lead response, treatment-plan follow-up) with slug, tagline, summary and page URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = services.map((s) => ({
      slug: s.slug,
      name: s.name,
      shortName: s.shortName,
      tagline: s.tagline,
      summary: s.summary,
      url: `${SITE2}/services/${s.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SITE3 = "https://orthoautomate.online";
var get_service_default = defineTool3({
  name: "get_service",
  title: "Get service details",
  description: "Get the full public detail of one OrthoAutomate service: intro, outcomes, how it works, features, who it is best for, and its FAQs. Use list_services first to find the slug.",
  inputSchema: {
    slug: z.string().min(1).describe("Service slug, e.g. ai-receptionist, lead-response, treatment-followup.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const service = services.find((s) => s.slug === slug.trim().toLowerCase());
    if (!service) {
      return {
        content: [
          {
            type: "text",
            text: `No service found for slug "${slug}". Available slugs: ${services.map((s) => s.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const payload = { ...service, url: `${SITE3}/services/${service.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { service: payload }
    };
  }
});

// src/lib/mcp/tools/list-integrations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var SITE4 = "https://orthoautomate.online";
var list_integrations_default = defineTool4({
  name: "list_integrations",
  title: "List PMS integrations",
  description: "List the dental practice-management systems OrthoAutomate integrates with (Dentrix, Open Dental, Eaglesoft, Curve Dental), including supported capabilities and setup timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = integrations.map((i) => ({
      ...i,
      url: `${SITE4}/integrations/${i.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { integrations: items }
    };
  }
});

// src/lib/mcp/tools/search-faqs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SITE5 = "https://orthoautomate.online";
var allFaqs = () => {
  const fromServices = services.flatMap(
    (s) => s.faqs.map((f) => ({
      question: f.q,
      answer: f.a,
      source: s.shortName,
      url: `${SITE5}/services/${s.slug}`
    }))
  );
  const fromLanding = landingPages.flatMap(
    (p) => p.faqs.map((f) => ({
      question: f.q,
      answer: f.a,
      source: p.breadcrumbLabel,
      url: `${SITE5}/${p.slug}`
    }))
  );
  return [...fromServices, ...fromLanding];
};
var search_faqs_default = defineTool5({
  name: "search_faqs",
  title: "Search FAQs",
  description: "Search OrthoAutomate's published FAQ answers about pricing, setup time, integrations, HIPAA/compliance, AI call handling and results. Omit the query to get every FAQ.",
  inputSchema: {
    query: z2.string().describe("Keywords to match against questions and answers. Use an empty string for all FAQs."),
    limit: z2.number().int().min(1).max(50).describe("Maximum number of FAQs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.trim().toLowerCase();
    const terms = q.split(/\s+/).filter(Boolean);
    const scored = allFaqs().map((f) => {
      const haystack = `${f.question} ${f.answer}`.toLowerCase();
      const score = terms.length ? terms.reduce((acc, t) => acc + (haystack.includes(t) ? 1 : 0), 0) : 1;
      return { ...f, score };
    }).filter((f) => f.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map(({ score: _score, ...rest }) => rest);
    return {
      content: [{ type: "text", text: JSON.stringify(scored, null, 2) }],
      structuredContent: { faqs: scored, count: scored.length }
    };
  }
});

// src/lib/mcp/tools/list-case-studies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/data/caseStudies.ts
var caseStudies = [
  {
    slug: "mendoza-family-dental-42k",
    clientName: "Dr. Rachel Mendoza, DDS",
    clinic: "Mendoza Family Dental",
    location: "Phoenix, AZ \xB7 3 locations",
    size: "$2.1M / year production",
    service: "Treatment Plan Follow-Up",
    durationDays: 90,
    headline: "Recovered $42,000 in 90 days from unaccepted treatment plans",
    quote: "We recovered $42,000 in 90 days just from treatment plans we'd already diagnosed but never followed up on. The AI did the work my team never had time for.",
    metrics: [
      { value: "$42K", label: "Revenue recovered (90 days)" },
      { value: "23%", label: "Reactivation rate on stuck plans" },
      { value: "184", label: "Missed calls captured per month" }
    ],
    challenge: "Mendoza Family Dental had over 600 unaccepted treatment plans across three locations \u2014 implants, full arches, and large restorative cases \u2014 sitting untouched in Open Dental. The front desk was running flat-out on day-to-day operations and had no bandwidth for systematic follow-up.",
    solution: "We installed AI Treatment Plan Follow-Up integrated directly with Open Dental, prioritizing $3K+ cases first. Each patient received a personalized 60-day cadence referencing their specific procedure, with objection-handling content (financing, timing, sedation) and one-tap booking links. Clinical questions escalated to the team automatically.",
    result: "$42,000 of additional production booked in the first 90 days, a 23% reactivation rate on the prioritized $3K+ cohort, and zero added workload for the front desk. Sequences continue to compound month-over-month."
  },
  {
    slug: "north-shore-ortho-leads",
    clientName: "Dr. Marcus Patel, DMD",
    clinic: "North Shore Orthodontics",
    location: "Boston, MA \xB7 1 location",
    size: "$1.4M / year production",
    service: "Instant AI Lead Response",
    durationDays: 60,
    headline: "8\xD7 higher booking rate from Meta ads in 60 days",
    quote: "We were spending $6K/month on Facebook ads and getting maybe 4 booked consults. After OrthoAutomate, that same spend now books 30+ \u2014 same ads, same budget, just instant response.",
    metrics: [
      { value: "8\xD7", label: "Increase in booking rate" },
      { value: "<45s", label: "Average lead response time" },
      { value: "$0", label: "Additional ad spend required" }
    ],
    challenge: "North Shore Orthodontics was running $6K/month in Meta ads for Invisalign and braces consultations. Leads sat in the Facebook lead inbox for 4\u201324 hours before the front desk could reply \u2014 by then, parents had already booked competitors.",
    solution: "We connected Facebook Lead Ads directly to our AI lead-response engine. Every new lead got an SMS within 45 seconds, was qualified in 2\u20133 messages, and booked straight into the practice calendar. Ghosted leads entered a 14-day re-engagement sequence.",
    result: "Booked consults jumped from ~4/month to 32/month on identical ad spend \u2014 an 8\xD7 improvement in booking rate and roughly an 87% reduction in effective cost-per-booked-consult."
  },
  {
    slug: "lakeside-dental-receptionist",
    clientName: "Dr. Jennifer Walsh, DDS",
    clinic: "Lakeside Family Dentistry",
    location: "Tampa, FL \xB7 1 location",
    size: "$1.1M / year production",
    service: "24/7 AI Receptionist",
    durationDays: 30,
    headline: "Missed-call rate dropped from 31% to 2% in 30 days",
    quote: "We were losing 3 out of every 10 new-patient calls \u2014 usually during lunch or after 5. The AI receptionist picks up in under 2 seconds and books them straight into Dentrix. It's like adding a perfect front-desk hire for a fraction of one salary.",
    metrics: [
      { value: "31% \u2192 2%", label: "Missed-call rate" },
      { value: "72%", label: "Recovered calls that booked" },
      { value: "$11.4K", label: "Recovered production / month" }
    ],
    challenge: "Lakeside Dental was losing 31% of inbound calls \u2014 almost all during lunch, after 5pm, and on weekends. Each missed new-patient call represented $700\u2013$1,200 in first-visit production walking out the door.",
    solution: "We deployed our 24/7 AI Receptionist integrated with Dentrix and their RingCentral phone system. The AI handles overflow during peak hours and 100% of after-hours calls, books directly into the Dentrix schedule, and routes emergencies to the on-call line.",
    result: "Missed-call rate fell from 31% to 2% within 30 days. Of the recovered calls, 72% became booked appointments \u2014 adding ~$11,400/month in recovered production with zero additional staff."
  }
];

// src/lib/mcp/tools/list-case-studies.ts
var SITE6 = "https://orthoautomate.online";
var list_case_studies_default = defineTool6({
  name: "list_case_studies",
  title: "List case studies",
  description: "List OrthoAutomate's published client case studies with clinic, location, service used, headline metrics, challenge, solution and result.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = caseStudies.map((c) => ({
      ...c,
      url: `${SITE6}/case-studies/${c.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { caseStudies: items }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/data/articles.ts
var articles = [
  {
    slug: "missed-call-revenue-loss-dental-clinics",
    title: "How Much Revenue Are You Really Losing to Missed Calls?",
    summary: "Most private dental clinics lose $40,000\u2013$120,000 a year to missed calls \u2014 here's how to measure it and stop the leak in 72 hours.",
    author: "Jashim Uddin",
    publishedAt: "2026-04-22",
    updatedAt: "2026-05-01",
    readingMinutes: 6,
    tags: ["AI Receptionist", "Revenue Recovery", "Dental Operations"],
    intro: "If you've ever pulled your phone-system report and seen a double-digit missed-call percentage, you're not alone \u2014 and the dollar figure attached to those calls is almost always bigger than clinic owners expect. In this article we break down the real math and show what most clinics are quietly losing every month.",
    sections: [
      {
        heading: "The hidden math of a missed call",
        paragraphs: [
          "The average new-patient phone call in general dentistry is worth $600\u2013$1,200 in first-visit production. For ortho, implants, or full-arch consults, that single call can represent $4,000\u2013$25,000 in lifetime production.",
          "When 18\u201335% of inbound calls go unanswered (the typical range we see in audits), the cumulative monthly loss adds up fast \u2014 usually between $4,000 and $12,000 in walked-away production."
        ],
        subsections: [
          {
            heading: "Why missed calls happen \u2014 even with a great front desk",
            paragraphs: [
              "Front desks aren't the problem. Calls peak during huddles, lunch, and the 4\u20136 PM after-work spike \u2014 exactly when staff is thinnest. Add weekends, holidays, and snow days and you have a structural gap that no human team can close on its own."
            ]
          }
        ]
      },
      {
        heading: "How to measure your real loss this week",
        bullets: [
          "Pull your last 30 days of call logs from your VoIP provider (RingCentral, Mango, Weave, etc.).",
          "Count inbound calls answered vs. missed (include voicemail-only as missed).",
          "Multiply missed \xD7 your average new-patient value \xD7 your historical booking rate.",
          "That number is your monthly missed-call revenue leak."
        ]
      },
      {
        heading: "What a 24/7 AI receptionist actually changes",
        paragraphs: [
          "A well-trained AI receptionist answers in under two seconds, books directly into your calendar, and hands off to a human the moment empathy or clinical judgment is needed. Across our installs we typically see missed-call rates drop from 25%+ to under 3% \u2014 and 60\u201380% of the recovered calls turn into booked appointments."
        ]
      },
      {
        heading: "Next step: get the actual number for your clinic",
        paragraphs: [
          "We'll pull your call data, calculate your real missed-call loss in dollars, and show you exactly what an AI receptionist would recover. No pitch unless you ask for one."
        ]
      }
    ],
    internalLinks: [
      { label: "How our 24/7 AI Receptionist works", to: "/about#what-we-do" },
      { label: "Common questions about the AI receptionist", to: "/faq#how-does-ai-receptionist-work" },
      { label: "Get a free Revenue Leak Audit", to: "/?focus=missed-calls#audit" }
    ]
  },
  {
    slug: "treatment-plan-follow-up-recovery-playbook",
    title: "The Treatment Plan Follow-Up Playbook That Reactivates 15\u201325% of Stuck Cases",
    summary: "A step-by-step framework for reactivating unaccepted dental treatment plans using AI follow-up sequences over 30\u201360 days.",
    author: "Jashim Uddin",
    publishedAt: "2026-04-29",
    updatedAt: "2026-05-04",
    readingMinutes: 7,
    tags: ["Treatment Plans", "Patient Reactivation", "AI Follow-Up"],
    intro: "Every dental practice has a six- or seven-figure pile of unaccepted treatment plans sitting in their PMS. Most never get touched again after the initial conversation. Here's the exact follow-up framework we use to recover 15\u201325% of them.",
    sections: [
      {
        heading: "Why treatment plans go stale",
        paragraphs: [
          "Patients almost never say no \u2014 they say 'let me think about it,' 'I need to check with my spouse,' or 'I'll call you back.' Without a structured follow-up cadence, those plans quietly die in the PMS report."
        ]
      },
      {
        heading: "The 30\u201360 day reactivation cadence",
        subsections: [
          {
            heading: "Days 1\u20137: warm reminder",
            paragraphs: [
              "Personalized SMS referencing the specific procedure and recommended timeline, with a one-tap booking link. No discount, no pressure \u2014 just a helpful nudge."
            ]
          },
          {
            heading: "Days 8\u201321: objection handling",
            paragraphs: [
              "Address the top three objections we see across thousands of cases: cost (financing options), timing (procedure duration and recovery), and fear (sedation and pain management)."
            ]
          },
          {
            heading: "Days 22\u201360: value reinforcement",
            paragraphs: [
              "Share patient education content, before/after results when appropriate, and a final 'is now still not the right time?' check-in."
            ]
          }
        ]
      },
      {
        heading: "Prioritize $3K+ cases first",
        paragraphs: [
          "Not all unaccepted plans deserve equal attention. Sort by treatment value and start with implants, ortho, full arches, and large restorative cases. A 20% recovery rate on a $50,000 backlog is a $10,000 month."
        ]
      },
      {
        heading: "What to automate vs. what to keep human",
        paragraphs: [
          "Automate the follow-up cadence, scheduling links, and FAQ replies. Always escalate to a human the moment a patient asks a clinical question, requests a callback, or expresses frustration."
        ]
      }
    ],
    internalLinks: [
      { label: "How AI Treatment Plan Follow-Up works", to: "/about#what-we-do" },
      { label: "FAQ: services overview", to: "/faq#what-services-do-you-offer" },
      { label: "Get a treatment-plan-focused audit", to: "/?focus=treatment#audit" }
    ]
  },
  {
    slug: "ad-lead-response-time-dental-marketing",
    title: "Why 60-Second Lead Response Time Doubles Your Dental Ad ROI",
    summary: "Lead response time is the single highest-leverage variable in paid dental marketing \u2014 here's the data and how AI fixes it.",
    author: "Jashim Uddin",
    publishedAt: "2026-05-05",
    updatedAt: "2026-05-05",
    readingMinutes: 5,
    tags: ["Paid Ads", "Lead Response", "Conversion"],
    intro: "If your clinic runs Google or Facebook ads, the gap between when a lead submits a form and when you reply is the single biggest predictor of whether they book. The data on this is brutal \u2014 and most clinics are losing the auction before the front desk even sees the lead.",
    sections: [
      {
        heading: "The 5-minute cliff",
        paragraphs: [
          "Industry research consistently shows leads contacted within 5 minutes are roughly 100x more likely to qualify than those contacted after 30 minutes. The drop-off is exponential, not linear."
        ]
      },
      {
        heading: "Why human-only follow-up loses",
        paragraphs: [
          "Front desks are answering phones, handling check-ins, and managing the schedule. Ad leads land in an email inbox or CRM that nobody is monitoring in real time. By the time someone sees it, the lead has already messaged three competitors."
        ]
      },
      {
        heading: "What instant AI lead response changes",
        bullets: [
          "Replies in under 60 seconds, 24/7, across SMS, Instagram DM, and Facebook Messenger.",
          "Qualifies the lead with 2\u20133 conversational questions.",
          "Books straight into the calendar or hands off to a human with full context.",
          "Re-engages ghosted leads automatically over 7\u201314 days."
        ]
      },
      {
        heading: "The compounding effect on ad spend",
        paragraphs: [
          "When booking rates double, your effective cost-per-acquisition is cut in half \u2014 without changing your ad budget, creative, or targeting. That's why lead response is the highest-ROI lever in dental marketing."
        ]
      }
    ],
    internalLinks: [
      { label: "How Instant AI Lead Response works", to: "/about#what-we-do" },
      { label: "FAQ: how do I get started?", to: "/faq#how-do-i-get-started" },
      { label: "Get a lead-response-focused audit", to: "/?focus=leads#audit" }
    ]
  },
  {
    slug: "dental-revenue-leakage",
    title: "Dental Revenue Leakage: The Three Hidden Drains Every Private Practice Has",
    summary: "Most private dental clinics quietly leak $80K\u2013$150K a year through missed calls, slow lead response, and unaccepted treatment plans \u2014 here's how to find and stop each one.",
    author: "Jashim Uddin",
    publishedAt: "2026-05-12",
    updatedAt: "2026-05-30",
    readingMinutes: 7,
    tags: ["Revenue Leakage", "Dental Operations", "AI Automation"],
    intro: "Dental revenue leakage is the gap between the production a practice could be booking and what it actually books. For most private clinics doing $800K\u2013$3M/year, that gap is between $80,000 and $150,000 every year \u2014 and it's almost always concentrated in three places. This article walks through each leak, how to measure it, and what to do about it.",
    sections: [
      {
        heading: "Leak #1: Missed inbound calls",
        paragraphs: [
          "The average private dental practice misses 18\u201335% of inbound calls. The losses concentrate during huddles, lunch, the after-work spike, weekends, and holidays \u2014 exactly when staffing is thinnest.",
          "Each missed new-patient call is worth $600\u2013$1,200 in first-visit production. For ortho, implants, or full-arch consults, lifetime value rises to $4,000\u2013$25,000 per call. A clinic missing 60 calls a month is realistically leaking $4,000\u2013$12,000 in booked production."
        ],
        subsections: [
          {
            heading: "How to measure it this week",
            paragraphs: [
              "Pull the last 30 days of call logs from your VoIP. Count answered vs. missed (voicemail-only is missed). Multiply missed \xD7 your historical booking rate \xD7 your average new-patient value. That's your monthly leak."
            ]
          }
        ]
      },
      {
        heading: "Leak #2: Slow response to ad leads",
        paragraphs: [
          "Industry data is unambiguous: leads contacted within 5 minutes are roughly 100\xD7 more likely to qualify than leads contacted after 30 minutes. Most dental clinics reply in hours, sometimes days \u2014 while a competitor's auto-responder is already in the conversation."
        ],
        bullets: [
          "Pull your ad lead log and median response time.",
          "If it's over 5 minutes, your effective cost-per-booked-patient is probably 2\xD7 what it could be.",
          "Closing the gap to under 60 seconds typically doubles booking rate without changing ad spend."
        ]
      },
      {
        heading: "Leak #3: Unaccepted treatment plans",
        paragraphs: [
          "Every PMS has a quietly growing pile of diagnosed-but-unaccepted treatment plans. Patients rarely say no outright \u2014 they say 'let me think,' 'I'll check with my spouse,' or 'I'll call back.' Without a structured 30\u201360 day follow-up, those plans die.",
          "Reactivating 15\u201325% of a $200,000 backlog adds $30K\u2013$50K of production in the first 60 days. The plans already exist; nobody is touching them."
        ]
      },
      {
        heading: "How to stop all three leaks at once",
        paragraphs: [
          "Hiring more front-desk staff doesn't fix this \u2014 humans can't answer in 2 seconds 24/7 and can't run a methodical 30\u201360 day cadence on every patient. AI handles the structured 80% of this work; your front desk keeps doing the empathy and clinical pieces it's already good at.",
          "The fastest path: audit the dollar figure for your own clinic, then install AI workflows targeted at whichever leak is largest. Most practices fix the biggest leak first and add the next two over 60 days."
        ]
      }
    ],
    internalLinks: [
      { label: "Missed call recovery for dental clinics", to: "/missed-call-recovery-for-dental-clinics" },
      { label: "Treatment plan follow-up AI", to: "/treatment-plan-follow-up-ai" },
      { label: "Dental lead conversion AI", to: "/dental-lead-conversion-ai" },
      { label: "Estimate your leakage with the ROI calculator", to: "/roi-calculator" }
    ]
  },
  {
    slug: "how-to-reduce-missed-calls-in-dental-clinics",
    title: "How to Reduce Missed Calls in Dental Clinics: An Operator's Playbook",
    summary: "A practical, vendor-neutral framework for cutting dental clinic missed-call rates from 25%+ to under 5% \u2014 phone routing, staffing, scripts, and AI overflow.",
    author: "Jashim Uddin",
    publishedAt: "2026-05-15",
    updatedAt: "2026-05-30",
    readingMinutes: 8,
    tags: ["Missed Calls", "Front Desk Operations", "AI Receptionist"],
    intro: "If your missed-call rate is north of 15%, you have a five- to six-figure annual leak and an unhappy front desk. The fix is rarely 'hire more people' \u2014 it's a stack of small operational changes plus a 24/7 AI safety net for the calls humans physically can't cover.",
    sections: [
      {
        heading: "Step 1: Get the real number",
        paragraphs: [
          "Pull 30 days of VoIP call logs and bucket them by hour. Most clinics discover 60\u201380% of misses cluster in three windows: huddle (8\u20139am), lunch (12\u20131pm), and the after-work spike (4\u20136pm)."
        ]
      },
      {
        heading: "Step 2: Fix the obvious operational gaps",
        bullets: [
          "Move the huddle so the phone is staffed at 8am.",
          "Stagger lunch so the desk is never empty.",
          "Set a clean overflow path from extension 1 \u2192 2 \u2192 mobile so calls escalate before voicemail.",
          "Disable voicemail for the main line during business hours \u2014 it's a known booking killer."
        ]
      },
      {
        heading: "Step 3: Tighten the scripts",
        paragraphs: [
          "Calls that get answered but don't book are also misses. Use a 4-line opener that confirms name, reason, insurance, and offers two appointment times. Most practices we audit see a 10\u201315 point booking-rate lift from script changes alone."
        ]
      },
      {
        heading: "Step 4: Cover the impossible windows with AI",
        paragraphs: [
          "Even a perfect front desk can't answer at 2am on Sunday. A 24/7 AI receptionist picks up in under 2 seconds, books directly into your PMS, and hands off to a human when judgment is needed. Across our installs, missed-call rates drop from 25%+ to under 3% and 60\u201380% of recovered calls book."
        ]
      },
      {
        heading: "Step 5: Measure monthly, not yearly",
        paragraphs: [
          "Add 'missed-call rate' and 'recovered-call bookings' to your monthly KPI report. If the number drifts back up, you'll see it immediately instead of at year-end."
        ]
      }
    ],
    internalLinks: [
      { label: "Missed call recovery for dental clinics", to: "/missed-call-recovery-for-dental-clinics" },
      { label: "Compare manual vs AI follow-up", to: "/compare/manual-follow-up-vs-ai" },
      { label: "Calculate missed-call revenue loss", to: "/roi-calculator" }
    ]
  },
  {
    slug: "how-ai-follows-up-treatment-plans",
    title: "How AI Follows Up on Dental Treatment Plans (Without Discounting or Spamming)",
    summary: "The exact 30\u201360 day cadence we use to reactivate 15\u201325% of unaccepted dental treatment plans \u2014 message timing, objection handling, and what to never automate.",
    author: "Jashim Uddin",
    publishedAt: "2026-05-20",
    updatedAt: "2026-05-30",
    readingMinutes: 7,
    tags: ["Treatment Plan Follow-Up", "AI Workflows", "Patient Communication"],
    intro: "Following up on unaccepted treatment plans is the highest-ROI work most dental practices never do consistently. AI changes that \u2014 but only if the cadence is designed around how patients actually decide, not around blasting messages. Here's the structure that works.",
    sections: [
      {
        heading: "The patient psychology this is built around",
        paragraphs: [
          "Patients with unaccepted plans aren't saying no \u2014 they're saying 'not yet.' The three things blocking them are almost always cost (uncertainty about financing), timing (work, kids, recovery), and fear (sedation, pain, the unknown). A good cadence addresses each, one at a time."
        ]
      },
      {
        heading: "The 30\u201360 day cadence, step by step",
        subsections: [
          {
            heading: "Days 1\u20137: warm reminder",
            paragraphs: [
              "Personalized SMS referencing the specific procedure and recommended timeline, with a one-tap booking link. No discount. No pressure. Just a helpful nudge."
            ]
          },
          {
            heading: "Days 8\u201321: objection handling",
            paragraphs: [
              "Three short messages, each addressing one objection: financing (CareCredit/Sunbit/in-house), timing (real procedure duration vs. fear of it), and sedation/pain management."
            ]
          },
          {
            heading: "Days 22\u201345: value reinforcement",
            paragraphs: [
              "Patient-education content tied to the specific procedure. For implants: bone-loss progression. For ortho: timeline reality vs. perception. No selling \u2014 only honest information."
            ]
          },
          {
            heading: "Days 46\u201360: final soft check-in",
            paragraphs: [
              "A single 'is now still not the right time?' message that opens the door without pressure. Patients who don't engage are removed from the sequence and re-entered into longer-term recall."
            ]
          }
        ]
      },
      {
        heading: "What we never automate",
        bullets: [
          "Clinical questions \u2014 always escalate to a human.",
          "Discount requests \u2014 handled by the office manager case-by-case.",
          "Frustrated or distressed sentiment \u2014 instant human handoff with full context."
        ]
      },
      {
        heading: "Why this works without discounting",
        paragraphs: [
          "Discounting trains patients to wait for the next discount. Education plus financing options closes the same percentage of cases at full fee \u2014 and protects the next year's pricing."
        ]
      },
      {
        heading: "Realistic results",
        paragraphs: [
          "Across installs, 15\u201325% of unaccepted plans book within 60 days. On a $200,000 backlog, that's $30K\u2013$50K in recovered production in the first two months, with no new ad spend and no front-desk overhead."
        ]
      }
    ],
    internalLinks: [
      { label: "Treatment plan follow-up AI", to: "/treatment-plan-follow-up-ai" },
      { label: "Dormant patient reactivation", to: "/dormant-patient-reactivation" },
      { label: "Compare manual vs AI follow-up", to: "/compare/manual-follow-up-vs-ai" },
      { label: "Calculate reactivation revenue", to: "/roi-calculator" }
    ]
  }
];

// src/lib/mcp/tools/list-articles.ts
var SITE7 = "https://orthoautomate.online";
var list_articles_default = defineTool7({
  name: "list_articles",
  title: "List blog articles",
  description: "List OrthoAutomate blog articles with slug, title, one-sentence summary, author, publish/update dates and tags. Use get_article to read the full text.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = articles.map((a) => ({
      slug: a.slug,
      title: a.title,
      summary: a.summary,
      author: a.author,
      publishedAt: a.publishedAt,
      updatedAt: a.updatedAt,
      readingMinutes: a.readingMinutes,
      tags: a.tags,
      url: `${SITE7}/blog/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { articles: items }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SITE8 = "https://orthoautomate.online";
var get_article_default = defineTool8({
  name: "get_article",
  title: "Get blog article",
  description: "Read the full text of one OrthoAutomate blog article as markdown, including all sections and subsections. Use list_articles to find the slug.",
  inputSchema: {
    slug: z3.string().min(1).describe("Article slug from list_articles.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const article = articles.find((a) => a.slug === slug.trim().toLowerCase());
    if (!article) {
      return {
        content: [
          {
            type: "text",
            text: `No article found for slug "${slug}". Available slugs: ${articles.map((a) => a.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const lines = [
      `# ${article.title}`,
      "",
      `By ${article.author} \u2014 published ${article.publishedAt}, updated ${article.updatedAt}`,
      "",
      article.intro,
      ""
    ];
    for (const section of article.sections) {
      lines.push(`## ${section.heading}`, "");
      for (const p of section.paragraphs ?? []) lines.push(p, "");
      for (const b of section.bullets ?? []) lines.push(`- ${b}`);
      if (section.bullets?.length) lines.push("");
      for (const sub of section.subsections ?? []) {
        lines.push(`### ${sub.heading}`, "");
        for (const p of sub.paragraphs) lines.push(p, "");
      }
    }
    const markdown = lines.join("\n").trim();
    const url = `${SITE8}/blog/${article.slug}`;
    return {
      content: [{ type: "text", text: `${markdown}

Source: ${url}` }],
      structuredContent: { slug: article.slug, title: article.title, url, markdown }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "orthoautomate-mcp",
  title: "OrthoAutomate",
  version: "0.1.0",
  instructions: "Public tools for OrthoAutomate, an AI revenue-recovery service for dental and orthodontic clinics. Start with `get_company_info` for an overview and the page map. Use `list_services` / `get_service` for service detail, `list_integrations` for supported practice-management systems (Dentrix, Open Dental, Eaglesoft, Curve Dental), `search_faqs` for pricing, setup, compliance and results questions, `list_case_studies` for client outcomes, and `list_articles` / `get_article` to read published articles. All data is public marketing content from orthoautomate.online.",
  tools: [
    get_company_info_default,
    list_services_default,
    get_service_default,
    list_integrations_default,
    search_faqs_default,
    list_case_studies_default,
    list_articles_default,
    get_article_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
